### PR TITLE
Fix `tag.attributes(nil)` throwing error

### PR DESCRIPTION
**Pull request by domchristie**

### CODE REVIEW

**Comment by seanpdoyle** [comment]
@domchristie thank you for opening this. I've added some test coverage, does that test case reproduce the situation where you encountered this error?

**Comment by domchristie** [comment]
@seanpdoyle yep, spot on! Thanks!

**Comment by seanpdoyle** [comment]
Could you add a commit message that outlines the scenario and issue you encountered?

**Review by seanpdoyle — APPROVED** [review]

**Comment by domchristie** [comment]
Unfortunately I’m away from my computer for a few days, and can’t remember the exact case, but I’ll have a look when I’m back on it

**Comment by domchristie** [comment]
> Could you add a commit message that outlines the scenario and issue you encountered?

I've amended that commit. Hopefully that clarifies the scenario.

**Pull request merged**
